# -*- mode: ruby -*-
# vi: set ft=ruby :

base_box = ENV.fetch('BASE_BOX')
box_version = ENV.fetch('BOX_VERSION')
docker_version = ENV.fetch('DOCKER_VERSION')

Vagrant.configure("2") do |config|
  config.vm.box = base_box
  config.vm.box_version = box_version
  config.vm.box_check_update = false

  config.vm.provision "shell" do |s|
    s.path = "customize.sh"
    s.env = {
        "DOCKER_VERSION" => docker_version
    }
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get clean
    sudo dd if=/dev/zero of=/EMPTY bs=1M 2>/dev/null || true
    sudo rm -f /EMPTY
    cat /dev/null > ~/.bash_history && history -c && exit
  SHELL

end

