#!/bin/sh

# This logic is to make sure, we can build directly from CLI
if [ -z ${VERSION_SET+x} ];then
    source $(dirname $0)/version
fi

source $(dirname $0)/variables

cd $(dirname $0)/../box

REPO=${REPO:-"leodotcloud"}
BOX=${BOX}
PROVIDER="virtualbox"

echo "Publishing vagrant box"
if [ -z ${DRY_RUN+x} ];then
  vagrant cloud auth login --token ${VAGRANT_TOKEN}
  vagrant cloud publish ${REPO}/${BOX} ${VERSION} ${PROVIDER} ./box/${OUTPUT_BOX} --release --force
else
  echo "vagrant cloud publish ${REPO}/${BOX} ${VERSION} ${PROVIDER} ./box/${OUTPUT_BOX} --release --force"
  echo "dry run, no action taken"
fi
