#!/bin/sh -x

# version.env file needs to be generated and sourced in
# downstream steps as some of the images don't have git
# and other necessary commands available

OS=${OS:-linux}
OS=$(echo "${OS}" | tr '[:upper:]' '[:lower:]')
echo "OS: ${OS}"

# These need to be "exported" as they are used in Vagrantfile
export DOCKER_VERSION=20.10
export BOX_VERSION=$(cat box_version)

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=$(git tag -l --contains HEAD | head -n 1)

if [ -z ${DIRTY+x} ] & [ -n "$GIT_TAG" ]; then
    VERSION=${GIT_TAG}
else
    VERSION="${BOX_VERSION}-${COMMIT}${DIRTY}"
fi

if [ -z ${ARCH+x} ]; then
    ARCH=amd64
fi



# TODO: Check if this is needed when using GitHub actions
rm -f version.env
touch version.env
tee -a version.env > /dev/null << EOT
export VERSION_SET=true
export OS=${OS}
export VERSION=${VERSION}
export ARCH=${ARCH}
export BOX_VERSION=${BOX_VERSION}
export DOCKER_VERSION=${DOCKER_VERSION}
EOT
echo "Generated version.env"
